Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.figure(figsize=(12,12))

N = 5
for i in range(0,N**2):
    plt.subplot(N,N,i+1)
    index = np.random.randint(0,A.shape[0])
    proj = A[index,:].reshape(82,82)
    plt.spy(proj)

plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 7[0m
[1;32m      5[0m     plt[38;5;241m.[39msubplot(N,N,i[38;5;241m+[39m[38;5;241m1[39m)
[1;32m      6[0m     index [38;5;241m=[39m np[38;5;241m.[39mrandom[38;5;241m.[39mrandint([38;5;241m0[39m,A[38;5;241m.[39mshape[[38;5;241m0[39m])
[0;32m----> 7[0m     proj [38;5;241m=[39m [43mA[49m[43m[[49m[43mindex[49m[43m,[49m[43m:[49m[43m][49m[38;5;241m.[39mreshape([38;5;241m82[39m,[38;5;241m82[39m)
[1;32m      8[0m     plt[38;5;241m.[39mspy(proj)
[1;32m     10[0m plt[38;5;241m.[39mshow()

[0;31mTypeError[0m: 'coo_matrix' object is not subscriptable

